name: .NET Core deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    # dotnet build and publish
    - name: Build with dotnet
      run: (cd RuralGroceryBlazor/ && dotnet build --configuration Release)
    - name: Test with dotnet
      run: (cd RuralGroceryBlazor/ && dotnet test)
    - name: Create executable with dotnet
      run: (cd RuralGroceryBlazor/ && dotnet publish -c Release -o RuralGroceryBlazor)
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: RuralGroceryNetwork
        publish-profile: ${{ secrets.AzurePublishProfile }}
        package: './RuralGroceryBlazor/RuralGroceryBlazor' 
