name: .NET Core

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: (cd RuralGroceryBlazor/ && dotnet build)
    - name: Test with dotnet
      run: (cd RuralGroceryBlazor/ && dotnet test)
